[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["a1z"]
artifacts = [
    "a1z/py.typed",
    "a1z/robot_models/**/*.urdf",
]

[tool.hatch.version]
source = "vcs"

[project]
name = "a1z"
dynamic = ["version"]
description = "Python SDK for the Galaxea A1Z 6-DOF robotic arm"
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE" }
authors = [{ name = "Galaxea" }]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "python-can>=4.0",
    "pin",
]

[project.urls]
Documentation = "https://github.com/userguide-galaxea/GALAXEA-A1Z#readme"
Source = "https://github.com/userguide-galaxea/GALAXEA-A1Z"
Tracker = "https://github.com/userguide-galaxea/GALAXEA-A1Z/issues"

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.ruff]
line-length = 119
lint.select = [
    "E",
    "F",
    "I",
]
lint.ignore = [
    "E501",
    "E741",
    "F841",
]
